
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 03 04:25:04 CST 2020
//----------------------------------------------------

package gramaticaLEN;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ampersand = 45;
  public static final int lanzamiento = 6;
  public static final int llave_b = 38;
  public static final int llave_a = 37;
  public static final int coma = 2;
  public static final int igual = 34;
  public static final int soloLetra = 44;
  public static final int letra = 35;
  public static final int terminal1 = 26;
  public static final int guion = 19;
  public static final int caracter = 42;
  public static final int tipoCadena = 30;
  public static final int dos_puntos = 8;
  public static final int result = 47;
  public static final int extension = 7;
  public static final int numero = 32;
  public static final int comentario_b = 25;
  public static final int comentario_a = 24;
  public static final int idMay = 40;
  public static final int EOF = 0;
  public static final int punto_coma = 9;
  public static final int comillas = 16;
  public static final int mas = 15;
  public static final int noTerminal = 27;
  public static final int nombre = 3;
  public static final int error = 1;
  public static final int por = 14;
  public static final int punto = 41;
  public static final int autor = 5;
  public static final int id = 33;
  public static final int parentesis_b = 18;
  public static final int parentesis_a = 17;
  public static final int guion_bajo = 48;
  public static final int o = 36;
  public static final int comentario = 23;
  public static final int separador = 10;
  public static final int espacio = 22;
  public static final int tab = 21;
  public static final int version = 4;
  public static final int tipoEntero = 28;
  public static final int resto = 43;
  public static final int enter = 20;
  public static final int agrupacion_b = 12;
  public static final int agrupacion_a = 11;
  public static final int tipoReal = 29;
  public static final int interrogacion = 13;
  public static final int idMin = 39;
  public static final int diagonal = 46;
  public static final int cadena = 31;
}

