/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import LALR.Estados;
import LALR.NodoCaso;
import hojas.NuevaHoja;
import java.io.*;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import pollitos.MisExpresiones;

/**
 *
 * @author luisGonzalez
 */
public class Inicio extends javax.swing.JFrame {

    private MisExpresiones expresion;
    
    //Estos arraylist lo mas probable es que sean temporales (BORRADOS CON EL TIEMPO)
    private ArrayList<MisExpresiones> listExpresion = new ArrayList<>();
    private ArrayList<Estados> listEstados = new ArrayList<>();
    private ArrayList<NodoCaso> listCasos = new ArrayList<>();
     
    
    
    private NuevaHoja nueva = new NuevaHoja();
    String a = "\\n";
    
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuGuardar2 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuComp = new javax.swing.JMenuItem();
        menuCargar = new javax.swing.JMenuItem();
        menuBorrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuLARL = new javax.swing.JMenuItem();
        menuPila = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(menuNuevo);

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);

        menuGuardar.setText("Guardar");
        jMenu1.add(menuGuardar);

        menuGuardar2.setText("Guardar como");
        jMenu1.add(menuGuardar2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lenguajes");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ejecutar");

        menuComp.setText("Compilar");
        jMenu3.add(menuComp);

        menuCargar.setText("Cargar lenguaje");
        jMenu3.add(menuCargar);

        menuBorrar.setText("Borrar lenguaje");
        jMenu3.add(menuBorrar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ver");

        menuLARL.setText("LARL");
        jMenu4.add(menuLARL);

        menuPila.setText("Pila");
        jMenu4.add(menuPila);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        File archivoNuevo;
        JFileChooser chooser = new JFileChooser();
        String seleccion = "Seleccione un archivo";
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle(seleccion);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile(): " + chooser.getSelectedFile());
            archivoNuevo = new File(chooser.getSelectedFile().getAbsolutePath());
            FileReader reader = null;
            BufferedReader buffer = null;
            String texto = "";
            nueva.crearHoja(archivoNuevo, reader, buffer, texto, tabbed, listExpresion, listEstados, listCasos);
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        PanelHojas panel = new PanelHojas("", "", listExpresion, listEstados, listCasos);
        tabbed.addTab("Sin nombre", panel);
        tabbed.setTabComponentAt(tabbed.getTabCount() - 1, nueva.crearCabecera("Sin nombre", tabbed));
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuBorrar;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenuItem menuComp;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuGuardar2;
    private javax.swing.JMenuItem menuLARL;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenuItem menuPila;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables
}
