/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Automata.Transiciones;
import Graficas.GraficaPila;
import LALR.FuncionesTabla;
import hojas.NumeracionLineas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pollitos.DatosGuardado;
import pollitos.Lenguajes;
import pollitos.Token;

/**
 *
 * @author luisGonzalez
 */
public class PanelHojas extends javax.swing.JPanel {

    public static String pilaHTML = "";
    private NumeracionLineas numeracion;
    private NumeracionLineas numeracion2;

    public static String totalErrores = "";

    private FuncionesTabla funciones = new FuncionesTabla();
    private Transiciones transicion = new Transiciones();
    private ArrayList<Token> listTokens = new ArrayList<>();
    private GraficaPila graficaPila = new GraficaPila();
    private Lenguajes elegido;
    private int noPanel;
    private String path;
    private ArrayList<DatosGuardado> listTextos;
    public static String todoBien = "";

    /**
     * Creates new form PanelHojas
     */
    public PanelHojas(String texto, String path, Lenguajes elegido, int noPanel, ArrayList<DatosGuardado> listTextos) {
        initComponents();
        txtCodigo.setText(texto);
        this.elegido = elegido;
        this.noPanel = noPanel;
        this.listTextos = listTextos;
        this.path = path;
        System.out.println(path);
        if (listTextos.size() <= noPanel) {
            listTextos.add(new DatosGuardado(texto, path));
            
        } else {
            listTextos.set(noPanel, new DatosGuardado(texto, path));
        }
        System.out.println("ACABAS DE ENTRAR AL PANEL NO: " + noPanel);
        numeracion = new NumeracionLineas(txtCodigo);
        numeracion2 = new NumeracionLineas(estado);
        jScrollPane1.setRowHeaderView(numeracion);
        jScrollPane2.setRowHeaderView(numeracion2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        estado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jScrollPane1.setViewportView(txtCodigo);

        jButton4.setText("Compilar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        estado.setColumns(20);
        estado.setRows(5);
        jScrollPane2.setViewportView(estado);

        jButton1.setText("Ver Pila");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    int i = 0;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (elegido != null) {
            listTokens = new ArrayList<>();
            listTextos.set(noPanel, new DatosGuardado(txtCodigo.getText(), path));
            String[] lineas = txtCodigo.getText().split("\n");
            String texto = "";
            for (String linea : lineas) {
                texto += linea;
            }
            String[] tab = texto.split("\t");
            texto = "";
            for (String string : tab) {
                texto += string;
            }
            transicion.transicionCadena(listTokens, elegido.getUnico().getListEstados().get(0), elegido.getUnico().getListEstados(), texto, elegido.getUnico().getTablaSiguientes());
            for (int j = 0; j < listTokens.size(); j++) {
                System.out.println("Cadena:  " + listTokens.get(j).getIdentificador() + " " + listTokens.get(j).getValor().toString());
            }
            funciones.transiciones(listTokens, elegido.getMiTabla(), elegido.getListSimbolos(), elegido.getListEstados(), elegido.getMiCodigo());

            if (totalErrores.equals("")) {
                estado.setText(todoBien);
            } else {
                estado.setText(totalErrores);
            }
            totalErrores = "";
            todoBien = "";
        } else {
            JOptionPane.showMessageDialog(null, "No has elegido un lenguaje aun.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        graficaPila.generarPilaHTML();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        estado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextArea estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables
}
